# Generated by Django 3.2 on 2022-03-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('first_number', models.IntegerField(null=True)),
                ('balance_group', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unique_number', models.IntegerField(unique=True)),
                ('initial_cost', models.IntegerField(null=True)),
                ('residual_value', models.IntegerField(null=True)),
                ('category', models.ForeignKey(on_delete=models.Model, to='shop_app.category')),
            ],
        ),
    ]
